{% set python_min = "3.10" %}
{% set name = "baybe" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/baybe-{{ version }}.tar.gz
  sha256: bb9bff53d841bcb07ce9cc29a13e57609964874fdd809b6a5fe0472c56b30b4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - joblib >1.4.0,<2
    - typing_extensions >=4.7.0
    - python >={{ python_min }},<3.13
    - attrs >=24.1.0
    - botorch >=0.13.0,<1
    - cattrs >=25.2.0
    - exceptiongroup
    - funcy >=1.17,<2
    - gpytorch >=1.9.1,<2
    - ngboost >=0.3.12,<1
    - numpy >=1.24.1,<3
    - pandas >=1.4.2,<3
    - protobuf >=3.20.3
    - scikit-learn >=1.1.1,<2
    - scipy >=1.10.1
    - setuptools-scm >=7.1.0
    - pytorch >=1.13.1,<3
    - typing-extensions >=4.7.0
    - opentelemetry-sdk >=1.16.0,<2
    - opentelemetry-propagator-aws-xray >=1.0.0,<2
    - opentelemetry-exporter-otlp >=1.16.0,<2
    - opentelemetry-sdk-extension-aws >=2.0.0,<3

test:
  imports:
    - baybe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://emdgroup.github.io/baybe/
  summary: A Bayesian Back End for Design of Experiments
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
