schema_version: 1

context:
  name: baybe
  version: 0.15.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/baybe-${{ version }}.tar.gz
  sha256: c74858b6daee8dfcbddbb4d2113d033d8179c6f82565d4e51cea8ca546fbdecb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - joblib >1.4.0,<2
    - typing_extensions >=4.7.0
    - python >=${{ python_min }},<3.13
    - attrs >=26.1.0
    - botorch >=0.13.0,<1
    - cattrs >=25.2.0
    - exceptiongroup
    - gpytorch >=1.9.1,<2
    - numpy >=1.24.1,<3
    - pandas >=2.1.0,<4
    - scikit-learn >=1.1.1,<2
    - scipy >=1.10.1
    - pytorch >=1.13.1,<3
tests:
  - python:
      imports:
        - baybe
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A Bayesian Back End for Design of Experiments
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://emdgroup.github.io/baybe/

extra:
  recipe-maintainers:
    - jan-janssen
